PROJETO_FUP_Brasil/Models/Cursos.cs
using Remake_FUP.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace PROJETO_FUP_Brasil.Models
{
    public class Cursos
    {
        [Key]
        public int Id_Curso { get; set; }
        [Required(ErrorMessage = "Campo obrigatório")]
        [RegularExpression(@"^[a-zA-Z ]*$", ErrorMessage = "Nome inválido")]
        [StringLength(60, MinimumLength = 3, ErrorMessage = "Tamanho inválido")]
        public string NomeCurso { get; set; }
        [Required(ErrorMessage = "Campo obrigatório")]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "Valor inválido")]
        public decimal ValorCurso { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        [RegularExpression(@"^[a-zA-Z ]*$", ErrorMessage = "Nome inválido")]
        [StringLength(60, MinimumLength = 3, ErrorMessage = "Tamanho inválido")]
        public string ProfessorCurso { get; set; }
        [InverseProperty("Cursos")]
        public virtual List<Aluno> Aluno { get; set; }



    }
}

PROJETO_FUP_Brasil/Controllers/CursosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using PdfSharpCore.Drawing;
using PROJETO_FUP_Brasil.Data;
using PROJETO_FUP_Brasil.Models;
using Remake_FUP.Models;

namespace PROJETO_FUP_Brasil.Controllers
{
    public class CursosController : Controller
    {
        private readonly PROJETO_FUP_BrasilContext _context;

        public CursosController(PROJETO_FUP_BrasilContext context)
        {
            _context = context;
        }

        // GET: Cursos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cursos.ToListAsync());
        }

        // GET: Cursos/Details/5
        [Authorize(Policy = "Admins")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cursos = await _context.Cursos
                .FirstOrDefaultAsync(m => m.Id_Curso == id);
            if (cursos == null)
            {
                return NotFound();
            }
            //var conteudoCurso = await _context.Aluno.ToListAsync();
            //ViewBag.Alunos = conteudoCurso;

            var listAlunos = await _context.Aluno.Include(d => d).ToListAsync();
            Cursos Curso = new Cursos();
            Curso.Aluno = listAlunos;


            return View(cursos);
        }

        // GET: Cursos/Create
        [Authorize(Policy = "Admins")]

        public IActionResult Create()
        {
            return View();
        }

        // POST: Cursos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id_Curso,NomeCurso,ValorCurso,ProfessorCurso")] Cursos cursos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cursos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cursos);
        }

        // GET: Cursos/Edit/5
        [Authorize(Policy = "Admins")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cursos = await _context.Cursos.FindAsync(id);
            if (cursos == null)
            {
                return NotFound();
            }
            return View(cursos);
        }

        // POST: Cursos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Admins")]

        public async Task<IActionResult> Edit(int id, [Bind("Id_Curso,NomeCurso,ValorCurso,ProfessorCurso")] Cursos cursos)
        {
            if (id != cursos.Id_Curso)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cursos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CursosExists(cursos.Id_Curso))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cursos);
        }

        // GET: Cursos/Delete/5
        [Authorize(Policy = "Admins")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cursos = await _context.Cursos
                .FirstOrDefaultAsync(m => m.Id_Curso == id);
            if (cursos == null)
            {
                return NotFound();
            }

            return View(cursos);
        }

        // POST: Cursos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Admins")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cursos = await _context.Cursos.FindAsync(id);
            _context.Cursos.Remove(cursos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CursosExists(int id)
        {
            return _context.Cursos.Any(e => e.Id_Curso == id);
        }

        public async Task<FileResult> DownloadAluno()
        {
            using (var doc = new PdfSharpCore.Pdf.PdfDocument())
            {
                var page = doc.AddPage();
                page.Size = PdfSharpCore.PageSize.A4;
                page.Orientation = PdfSharpCore.PageOrientation.Portrait;
                var graphics = PdfSharpCore.Drawing.XGraphics.FromPdfPage(page);
                var corFonte = PdfSharpCore.Drawing.XBrushes.Black;
                var textFormatter = new PdfSharpCore.Drawing.Layout.XTextFormatter(graphics);
                var fonteOrganizacao = new PdfSharpCore.Drawing.XFont("Ariel", 10);
                var fonteDescricao = new PdfSharpCore.Drawing.XFont("Ariel", 8, PdfSharpCore.Drawing.XFontStyle.BoldItalic);
                var tituloDetalhes = new PdfSharpCore.Drawing.XFont("Ariel", 8, PdfSharpCore.Drawing.XFontStyle.Bold);
                var fonteDetalhesDescricao = new PdfSharpCore.Drawing.XFont("Ariel", 7);
                var logo = @"C:\Users\Aparicio\Desktop\FUP_TRABALHO_29-05\PROJETO_FUP_Brasil\wwwroot\img\logo.jpg";
                var qtdPaginas = doc.PageCount;

                //imagem logotipo
                textFormatter.DrawString(qtdPaginas.ToString(), new PdfSharpCore.Drawing.XFont("Arial", 10), corFonte, new PdfSharpCore.Drawing.XRect(575, 825, page.Width, page.Height));
                XImage imagem = XImage.FromFile(logo);
                graphics.DrawImage(imagem, 20, 5, 100, 50);


                //Titulo Maior
                var descricaoFinanceira = new PdfSharpCore.Drawing.Layout.XTextFormatter(graphics);
                descricaoFinanceira.Alignment = PdfSharpCore.Drawing.Layout.XParagraphAlignment.Center;
                descricaoFinanceira.DrawString("Alunos do Curso", tituloDetalhes, corFonte, new PdfSharpCore.Drawing.XRect(0, 120, page.Width, page.Height));

                //titulo das Colunas
                var alturaTituloFinanceiroY = 140;
                var detalhes = new PdfSharpCore.Drawing.Layout.XTextFormatter(graphics);

                detalhes.DrawString("Aluno", fonteDescricao, PdfSharpCore.Drawing.XBrushes.Red, new PdfSharpCore.Drawing.XRect(20, alturaTituloFinanceiroY, page.Width, page.Height));
                detalhes.DrawString("Curso", fonteDescricao, PdfSharpCore.Drawing.XBrushes.Green, new PdfSharpCore.Drawing.XRect(220, alturaTituloFinanceiroY, page.Width, page.Height));

                //gerar dados do relátorio

                Cursos model = new Cursos();
                var alturaItens = 160;
                var alturaItens2 = 160;
                var conteudoAluno = await _context.Aluno.Include(d => d.Cursos).ToListAsync();
                model.Aluno = conteudoAluno;

                if(model.Aluno != null){

                foreach (var item in model.Aluno)
                {
                    textFormatter.DrawString("Aluno: " + item.Nome, fonteDescricao, corFonte, new PdfSharpCore.Drawing.XRect(20, alturaItens, page.Width, page.Height));
                    alturaItens += 20;
                }


                foreach (var item in model.Aluno)
                {
                    textFormatter.DrawString("Curso: " + item.Cursos.NomeCurso, fonteDescricao, corFonte, new PdfSharpCore.Drawing.XRect(220, alturaItens2, page.Width, page.Height));
                    alturaItens2 += 20;
                }
            }

            //cabeçalho inicio statico
            textFormatter.DrawString("Instituição: ", fonteDescricao, corFonte, new PdfSharpCore.Drawing.XRect(20, 95, page.Width, page.Height));
            textFormatter.DrawString("Faculdade Universitaria de Programação", fonteDescricao, corFonte, new PdfSharpCore.Drawing.XRect(80, 95, page.Width, page.Height));




            using (MemoryStream stream = new MemoryStream())
            {
                var contantType = "application/pdf";
                doc.Save(stream, false);
                var nomeArquivo = "relatorioFinancerio.pdf";
                return File(stream.ToArray(), contantType, nomeArquivo);
            }
        }
    }
}
}

PROJETO_FUP_Brasil/Controllers/FinanceiroViewModelsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR.Protocol;
using Microsoft.EntityFrameworkCore;
using PdfSharpCore.Drawing;
using PROJETO_FUP_Brasil.Data;
using PROJETO_FUP_Brasil.Models;
using Remake_FUP.Models;

namespace PROJETO_FUP_Brasil.Controllers
{
    public class FinanceirosController : Controller
    {
        private readonly PROJETO_FUP_BrasilContext _context;

        public FinanceirosController(PROJETO_FUP_BrasilContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var listAlunos = await _context.Aluno.Include(d => d.Cursos).ToListAsync();
            var listFuncionarios = await _context.Funcionario.ToListAsync();
            FinanceiroViewModel model = new FinanceiroViewModel();
            model.Alunos = listAlunos;
            model.Funcionarios = listFuncionarios;


            return View(model);
        }
        public async Task<FileResult> Download()
        {
            using (var doc = new PdfSharpCore.Pdf.PdfDocument())
            {
                var page = doc.AddPage();
                page.Size = PdfSharpCore.PageSize.A4;
                page.Orientation = PdfSharpCore.PageOrientation.Portrait;
                var graphics = PdfSharpCore.Drawing.XGraphics.FromPdfPage(page);
                var corFonte = PdfSharpCore.Drawing.XBrushes.Black;
                var textFormatter = new PdfSharpCore.Drawing.Layout.XTextFormatter(graphics);
                var fonteOrganizacao = new PdfSharpCore.Drawing.XFont("Ariel", 10);
                var fonteDescricao = new PdfSharpCore.Drawing.XFont("Ariel", 8, PdfSharpCore.Drawing.XFontStyle.BoldItalic);
                var tituloDetalhes = new PdfSharpCore.Drawing.XFont("Ariel", 8, PdfSharpCore.Drawing.XFontStyle.Bold);
                var fonteDetalhesDescricao = new PdfSharpCore.Drawing.XFont("Ariel", 7);
                var logo = @"C:\Users\Aparicio\Desktop\FUP_TRABALHO_29-05\PROJETO_FUP_Brasil\wwwroot\img\logo.jpg";
                var qtdPaginas = doc.PageCount;

                //imagem logotipo
                textFormatter.DrawString(qtdPaginas.ToString(), new PdfSharpCore.Drawing.XFont("Arial", 10), corFonte, new PdfSharpCore.Drawing.XRect(575, 825, page.Width, page.Height));
                XImage imagem = XImage.FromFile(logo);
                graphics.DrawImage(imagem, 20, 5, 100, 50);


                //Titulo Maior
                var descricaoFinanceira = new PdfSharpCore.Drawing.Layout.XTextFormatter(graphics);
                descricaoFinanceira.Alignment = PdfSharpCore.Drawing.Layout.XParagraphAlignment.Center;
                descricaoFinanceira.DrawString("Detalhamento Financeiro", tituloDetalhes, corFonte, new PdfSharpCore.Drawing.XRect(0, 120, page.Width, page.Height));

                //titulo das Colunas
                var alturaTituloFinanceiroY = 140;
                var detalhes = new PdfSharpCore.Drawing.Layout.XTextFormatter(graphics);

                detalhes.DrawString("Saida", fonteDescricao, PdfSharpCore.Drawing.XBrushes.Red, new PdfSharpCore.Drawing.XRect(20, alturaTituloFinanceiroY, page.Width, page.Height));
                detalhes.DrawString("Entrada", fonteDescricao, PdfSharpCore.Drawing.XBrushes.Green, new PdfSharpCore.Drawing.XRect(220, alturaTituloFinanceiroY, page.Width, page.Height));
                detalhes.DrawString("Total Liquido", fonteDescricao, PdfSharpCore.Drawing.XBrushes.CadetBlue, new PdfSharpCore.Drawing.XRect(340, alturaTituloFinanceiroY, page.Width, page.Height));

                //gerar dados do relátorio

                FinanceiroViewModel model = new FinanceiroViewModel();
                var alturaItens = 160;
                var alturaItens2 = 160;
                var conteudoAluno = await _context.Aluno.Include(d => d.Cursos).ToListAsync();
                var conteudoFuncionario = await _context.Funcionario.ToListAsync();
                model.Funcionarios = conteudoFuncionario;
                model.Alunos = conteudoAluno;
                decimal somaDespesas = 0;
                decimal somaLucros = 0;
                decimal totalLiquido = 0;


                foreach (var item in model.Funcionarios)
                {
                    textFormatter.DrawString("Saida: " + item.SalarioFuncionario, fonteDescricao, corFonte, new PdfSharpCore.Drawing.XRect(20, alturaItens, page.Width, page.Height));
                    somaDespesas += item.SalarioFuncionario;
                    alturaItens += 20;
                }


                foreach (var item in model.Alunos)
                {
                    textFormatter.DrawString("Entrada: " + item.Cursos.ValorCurso, fonteDescricao, corFonte, new PdfSharpCore.Drawing.XRect(220, alturaItens2, page.Width, page.Height));
                    somaLucros += item.Cursos.ValorCurso;
                    alturaItens2 += 20;
                }
                totalLiquido = somaLucros - somaDespesas;
                textFormatter.DrawString("Total Saida: " + somaDespesas, fonteDescricao, corFonte, new PdfSharpCore.Drawing.XRect(20, alturaItens, page.Width, page.Height));
                textFormatter.DrawString("Total Entrada: " + somaLucros, fonteDescricao, corFonte, new PdfSharpCore.Drawing.XRect(220, alturaItens2, page.Width, page.Height));
                if (totalLiquido > 0)
                {
                    textFormatter.DrawString("Total Liquido: " + totalLiquido, fonteDescricao, PdfSharpCore.Drawing.XBrushes.Green, new PdfSharpCore.Drawing.XRect(340, alturaItens2, page.Width, page.Height));
                }
                else
                {
                    textFormatter.DrawString("Total Liquido: " + totalLiquido, fonteDescricao, PdfSharpCore.Drawing.XBrushes.Red, new PdfSharpCore.Drawing.XRect(340, alturaItens2, page.Width, page.Height));
                }


                //cabeçalho inicio statico
                textFormatter.DrawString("Instituição: ", fonteDescricao, corFonte, new PdfSharpCore.Drawing.XRect(20, 95, page.Width, page.Height));
                textFormatter.DrawString("Faculdade Universitaria de Programação", fonteDescricao, corFonte, new PdfSharpCore.Drawing.XRect(80, 95, page.Width, page.Height));




                using (MemoryStream stream = new MemoryStream())
                {
                    var contantType = "application/pdf";
                    doc.Save(stream, false);
                    var nomeArquivo = "relatorioFinancerio.pdf";
                    return File(stream.ToArray(), contantType, nomeArquivo);
                }

            }
        }

    }


}

PROJETO_FUP_Brasil/Views/Cursos/Create.cshtml
@model PROJETO_FUP_Brasil.Models.Cursos

@{
    ViewData["Title"] = "Create";
}


<div class="container">
    <div class="row">
        <div class="col-md-12 text-center py-5">

        </div>
        <form asp-action="Create">
            <div class="row">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="col-md-12 roboto">
                    <div class="form-group">
                        <h2 class="roboto mr-5">Curso</h2>
                        <input asp-for="NomeCurso" class="form-control roboto" placeholder="NOME DO CURSO" />
                        <span asp-validation-for="NomeCurso" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6 roboto">
                    <h2 class="roboto mr-5">Mensalidade</h2>
                    <input asp-for="ValorCurso" class="form-control roboto" placeholder="MENSALIDADE" />
                    <span asp-validation-for="ValorCurso" class="text-danger"></span>
                </div>
                <div class="col-md-6 roboto mb-3">
                    <h2 class="roboto mr-5">Responsável do Curso</h2>
                    <input asp-for="ProfessorCurso" class="form-control" placeholder="COORDENADOR DO CURSO" />
                    <span asp-validation-for="ProfessorCurso" class="text-danger"></span>
                </div>
                <div class="form-group text-center col-md-12 w-100">
                    <input type="submit" value="ADICIONAR NOVO CURSO" class="btn-add w-50 rounded-pill" />
                    <a href="/Cursos">
                        <input class="roboto btn-voltar w-50 text-center rounded-pill mb-5" value="VOLTAR PARA O INICIO">
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>




<div>
   
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PROJETO_FUP_Brasil/Views/Cursos/Delete.cshtml
@model PROJETO_FUP_Brasil.Models.Cursos

@{
    ViewData["Title"] = "Delete";
}


<div>
    <div class="py-5"></div>
    <img class="position-absolute mt-5 pt-3 mx-5 ficha " src="~/img/ficha.png" />
    <div class="container back-detalhes pt-5 pb-3 ">
        <div class="row  p-6">
            <div class="pb-5 text-center">

            </div>
            <div class="col-md-12 text-left">
                <h2 class="text-uppercase">CURSO - <strong>@Html.DisplayFor(model => model.NomeCurso)</strong></h2>
            </div>
            <div class="col-md-12 py-3">
                <h2 class="text-uppercase">
                    VALOR - <strong>@Html.DisplayFor(model => model.ValorCurso)</strong>
                </h2>
            </div>
            <div class="col-md-12 ">
                <h2 class="text-uppercase">
                    COORDENADOR CURSO -  <strong>@Html.DisplayFor(model => model.ProfessorCurso)</strong>
                </h2>
            </div>
        </div>
    </div>
    <div class="pb-3 text-center">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <input type="hidden" asp-for="Id_Curso" />
                    <input type="submit" id="ifood" value="Excluir" class="roboto rounded-pill border-0 px-5 py-3 mt-5 mb-3 w-50 btn-deletar text-uppercase" />
                </div>
                <div class="col-md-12">
                    <a asp-action="Index"><button class="mb-3 btn-abrir roboto rounded-pill border-0 mb-5 px-5 py-3  w-50 ">VOLTAR</button></a>
                </div>
            </div>
        </div>

        <div class="popup-container">
            <div class="popup rounded">
                <div class="popup-close">x</div>
                <div class="popup-content">

                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <h2 class="my-3 roboto">Tem certeza de que deseja excluir estes dados?</h2>
                                <form asp-action="Delete">
                                    <input type="hidden" asp-for="Id_Curso" />
                                    <input type="submit" value="EXCLUIR" class="roboto rounded-pill border-0 px-5 py-3 mt-5 mb-3 w-50 btn-deletar text-uppercase" />
                                </form>
                            </div>

                            <div class="col-md-12">
                                <a asp-action="Index"><button class="mb-3 btn-abrir roboto rounded-pill border-0 mb-3 px-5 py-3  w-50 ">CANCELAR</button></a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>

</div>

<script>
        const button = document.getElementById('ifood');
        const popup = document.querySelector('.popup-container');
        const close = document.querySelector('.popup-close')
        button.addEventListener('click', () => {
            popup.style.display = 'flex';
        })
        close.addEventListener('click', () => {
            popup.style.display = 'none';
        })
        popup.addEventListener('click', () => {
            popup.style.display = 'none';
        });
        const button2 = document.getElementById('last');
        const popup2 = document.querySelector('.popup-container');
        const close2 = document.querySelector('.popup-close')
        button2.addEventListener('click', () => {
            popup2.style.display = 'flex';
        })
        close2.addEventListener('click', () => {
            popup2.style.display = 'none';
        })
        popup2.addEventListener('click', () => {
            popup2.style.display = 'none';
        })
</script>
@*<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.NomeCurso)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.NomeCurso)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.ValorCurso)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.ValorCurso)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.ProfessorCurso)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.ProfessorCurso)
    </dd>
</dl>

<form asp-action="Delete">
    <input type="hidden" asp-for="Id_Curso" />
    <input type="submit" value="Delete" class="btn btn-danger" /> |
    <a asp-action="Index">Back to List</a>
</form>*@*
</div>

PROJETO_FUP_Brasil/Views/Cursos/Details.cshtml
@model PROJETO_FUP_Brasil.Models.Cursos

@{
    ViewData["Title"] = "Details";

}
<div class="py-5"></div>
<img class="position-absolute mt-5 pt-3 mx-5 ficha " src="~/img/ficha.png" />
<div class="container back-detalhes pt-5 pb-3 ">
    <div class="row  p-6">
        <div class="pb-5 text-center">

        </div>
        <div class="col-md-12 text-left">
            <h2 class="text-uppercase">CURSO - <strong>@Html.DisplayFor(model => model.NomeCurso)</strong></h2>
        </div>
        <div class="col-md-12 py-3">
            <h2 class="text-uppercase">
                VALOR - <strong>@Html.DisplayFor(model => model.ValorCurso)</strong>
            </h2>
        </div>
        <div class="col-md-12 ">
            <h2 class="text-uppercase">
                COORDENADOR CURSO -  <strong>@Html.DisplayFor(model => model.ProfessorCurso)</strong>
            </h2>
        </div>
        <div class="col-md-12 py-3">
            <h2 class="text-uppercase">
                ALUNO CURSANDO  <strong>
    @if (Model.Aluno != null)
    {
        foreach (var item in Model.Aluno)
        {
            if (item.DataTerminoCurso == null || item.DataTerminoCurso.ToString() == "")
            {
                <dd class="col-sm-10 mt-3" style="margin-left: -18px;">
                    @Html.DisplayFor(modelItem => item.Nome)
                </dd>
              
            }
        }
    }
    else
    {
        <dd class="mt-3"style="font-size: 28px!important;">Nenhum aluno cadastrado no curso</dd>
    }
</strong>
            </h2>
        </div>
    </div>
</div>
<div class="pb-3 text-center">
    <a asp-action="Index"><button class="mb-3 btn-abrir roboto rounded-pill border-0 px-5 py-3 my-5 w-75 ">VOLTAR</button></a>
   
</div>


 

PROJETO_FUP_Brasil/Views/Cursos/Edit.cshtml
@model PROJETO_FUP_Brasil.Models.Cursos

@{
    ViewData["Title"] = "Edit";
}

<div class="container">
    <div class="row">
        <div class="col-md-12 text-center py-5">

        </div>
        <form asp-action="Edit">
            <div class="row">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id_Curso" />
                <div class="col-md-12 roboto">
                    <div class="form-group">
                        <h2 class="roboto mr-5">Curso</h2>
                        <input asp-for="NomeCurso" class="form-control roboto" placeholder="NOME DO CURSO" />
                        <span asp-validation-for="NomeCurso" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6 roboto">
                    <h2 class="roboto mr-5">Mensalidade</h2>
                    <input asp-for="ValorCurso" class="form-control roboto" placeholder="MENSALIDADE" />
                    <span asp-validation-for="ValorCurso" class="text-danger"></span>
                </div>
                <div class="col-md-6 roboto mb-3">
                    <h2 class="roboto mr-5">Responsável do Curso</h2>
                    <input asp-for="ProfessorCurso" class="form-control" placeholder="COORDENADOR DO CURSO" />
                    <span asp-validation-for="ProfessorCurso" class="text-danger"></span>
                </div>
                <div class="form-group text-center col-md-12 w-100">
                    <input type="submit" value="EDITAR CURSO" class="btn-add w-50 rounded-pill" />
                    <a href="/Cursos">
                        <input class="roboto btn-voltar w-50 text-center rounded-pill mb-5" value="VOLTAR PARA O INICIO">
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PROJETO_FUP_Brasil/Views/Cursos/Index.cshtml
@model IEnumerable<PROJETO_FUP_Brasil.Models.Cursos>

@{
    ViewData["Title"] = "Index";
}   

<div class="container">
    <div class="row">
        <div class="col-md-12 d-flex align-items-md-center">
            <div class="btn-1">
                <a asp-action="Create">
                    <button class="btn-criar roboto rounded-pill border-0">CADASTRAR</button>
                </a>
            </div>
            <div class="btn-2 ml-3">
                <a asp-area="" asp-controller="Cursos" asp-action="DownloadAluno"><button class="btn-criar roboto rounded-pill border-0 " asp-area="" asp-controller="Financeiros" asp-action="Download">GERAR RELÁTORIO</button></a>
            </div>
        </div>
    </div>
</div>   
    
<table  class="table roboto text-uppercase font-tabela">
    <thead>
        <tr>
            <th>
            CURSO
            </th>
            <th>
              MENSALIDADE
            </th>
            <th>
               CORDENADOR DO CURSO
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr class="table roboto text-uppercase font-tabela">
            <td>
                @Html.DisplayFor(modelItem => item.NomeCurso)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValorCurso)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProfessorCurso)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id_Curso" class="button-geral">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id_Curso" class="button-geral">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.Id_Curso" class="button-geral">Deletar</a>
            </td>
        </tr>
}
    </tbody>
</table>